### ISSUE TITLE
Implement Login and Signup Page with Provided Design

### ISSUE THREAD

**Issue by Ganeshshinde-2003** [Tech-Tribee/Fleet-Roving-Driver#1]
1.Develop a splash screen.
2. Develop login page based on the provided design with email/phone and password login options.
3. Create signup page following the design, allowing users to register with email/phone, password, and personal details.
4. Use the design provided [here](https://www.figma.com/proto/vWorYAAQLKAMXiPJJlljBd/Soft-UI-Dashboard-Free-(Community)-(Community)?type=design&node-id=104-89&t=y9hBJMHpmB2ga5bj-0&scaling=scale-down&page-id=4%3A47)

**Comment by amaranand360** [comment]
issues Resolve here link of pull request : [(https://github.com/Tech-Tribee/Fleet-Roving-Driver/pull/2)]
